export * from "./AppointmentsRepository"
export * from "./FAQRepository"
export * from "./PatientsRepository"
export * from "./USMRepository"
export * from "./VaccinesRepository"
export * from "./DiseaseRepository"
export * from "./HealthProtocolRepository"